### ISSUE TITLE
PopOS make files request

### ISSUE THREAD

**Issue by Lichtenbolt** [khampf/g13#3]
Works wonderfully in Manjaro.  Linux noob, nevertheless I tried building this with Cmake in PopOS.  Dependancies: libevdev was already there, libusb-1.0 installed as directed but the final make had problems with log4cpp (tried building it separately from Github and also by installing liblog4cpp5v5 which is readily available for ubuntu.  So what I’m asking for is either a little guidance or a make file that works in Ubuntu based distros please ?

**Comment by khampf** [comment]
It has been a long time since I did any packaging for deb-based Linux distributions but I will look into it shortly.

**Comment by khampf** [comment]
Debian packaging tools (APT) seem to be broken on Arch, it will have to wait for now but I will make an effort to package it later.

**Comment by khampf** [comment]
However, the only thing stopping me from making a package right now is that I do not have the time to install any Debian-based (like Ubuntu) distribution for doing this instead of just making the package straight from my Arch Linux setup - but if you would like to take a stab at it I suggest following instructions like theese: https://packaging.ubuntu.com/html/packaging-new-software.html

**Comment by Lichtenbolt** [comment]
No worries, I'm sure a lot of people on other distros would love your g13 solution outside of the AUR but since I am having problems with PopOS I've already moved back to Manjaro.  Thankyou for going as far as you did, I'll have a closer look and revist this when I run up another distro.
